#ifndef INCLUDE_PROTOCOL_H
#define INCLUDE_PROTOCOL_H

enum opcode {
    CLIENT_HELLO = 1,
    CLIENT_GOODBYE = 2,
    CLIENT_DRAW = 3,
    CLIENT_INVALID = 127,
    SERVER_ACTIVATED_CLIENT = 129,
    SERVER_ENQUEUED_CLIENT = 130,
    SERVER_GOODBYE = 131,
    SERVER_DRAW_SUCCESSFUL = 132,
    SERVER_DRAW_IMPOSSIBLE = 133,
    SERVER_DRAW_REFUSED = 134,
    SERVER_INVALID = 255,
};

#endif
